import os


def create_directory():
    if not os.path.exists('passwords'):
        os.mkdir('passwords')


def create_txt():
    with open('passwords/readme.txt', 'w') as db_manual_txt:
        db_manual_txt.write(
            'As you can see, there is a file called "your_passwords_database" in this directory.\n'
            'This file contains all data about passwords generated by "Password Generator.exe".\n'
            'And new data from the generator will be added to this file.\n'
            'If SQLite is not installed in your PC, you can open it using SQLite online viewers.\n'
            'For example, https://inloop.github.io/sqlite-viewer/ or https://sqliteonline.com/ .\n'
            'If the above websites do not work, you need to find any other or install SQLite on your PC.\n\n'
            
            'Як бачите, у цьому каталозі є файл під назвою "your_passwords_database"\n'
            'Цей файл містить усі дані про паролі, згенеровані "Password Generator.exe".\n'
            'Нові дані, які будуть створені в генераторі, також будуть додані в цей файл.\n'
            'Якщо SQLite не встановлено на ваш, ви можете відкрити його за допомогою онлайн переглядачів.\n'
            'Наприклад, https://inloop.github.io/sqlite-viewer/ або https://sqliteonline.com/ .\n'
            'Якщо вищенаведені веб-сайти не працюють, вам потрібно знайти будь-який інший або інсталювати SQLite.\n\n'
        )
